name: Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'  # Specify the JDK distribution (e.g., 'adoptopenjdk', 'zulu', etc.)

    - name: Set up Android SDK
      uses: reactivecircus/android-emulator-runner@v2

    - name: Run tests
      run: ./gradlew connectedAndroidTest