name: Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Correct distribution name

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        # Install required SDK packages
        yes | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator" "system-images;android-30;google_apis;x86_64"
        # Accept licenses
        yes | sdkmanager --licenses

    - name: Install Appium and dependencies
      run: |
        # Install Node.js (required for Appium)
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm
        
        # Install Appium globally
        sudo npm install -g appium
        # Optional: Check Appium setup
        appium-doctor --android

    - name: Start Android Emulator
      run: |
        # Start the Android emulator in the background
        nohup emulator -avd test_avd -no-skin -no-audio -no-window &
        # Wait for the emulator to start
        adb wait-for-device
        adb shell input keyevent 82  # Unlock the screen (optional)

    - name: Run Android Appium tests
      run: |
        # Navigate to your Maven project
        cd /path/to/your/java/appium/test  # Adjust the directory path to where your Maven project is
        mvn test -Dplatform=android  # Run tests via Maven for the Android platform