name: iOS Emulator

on:
  push:
    branches:
      - main

jobs:
  ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install

    - name: Run tests
      run: xcodebuild test -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 12'